/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    mentors: Mentor;
    mentees: Mentee;
    sessions: Session;
    messages: Message;
    transactions: Transaction;
    availability: Availability;
    'call-sessions': CallSession;
    withdrawals: Withdrawal;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    mentors: MentorsSelect<false> | MentorsSelect<true>;
    mentees: MenteesSelect<false> | MenteesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    'call-sessions': CallSessionsSelect<false> | CallSessionsSelect<true>;
    withdrawals: WithdrawalsSelect<false> | WithdrawalsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Select the user role. Only admins can change this.
   */
  role?: ('admin' | 'mentor' | 'mentee') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Mentor profiles — people studying or living abroad who guide prospective students.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors".
 */
export interface Mentor {
  id: string;
  /**
   * The user account that owns this mentor profile.
   */
  user: string | User;
  /**
   * Profile photo shown on the discovery page.
   */
  profileImage?: (string | null) | Media;
  /**
   * Admin-verified mentor badge.
   */
  isVerified?: boolean | null;
  /**
   * Toggle availability for new bookings.
   */
  isAvailable?: boolean | null;
  /**
   * Short headline, e.g. "MS Computer Science @ MIT — Living in USA since 2020".
   */
  headline: string;
  /**
   * Tell students about your journey abroad.
   */
  bio?: string | null;
  /**
   * Country where you are currently studying or living.
   */
  country:
    | 'usa'
    | 'uk'
    | 'canada'
    | 'australia'
    | 'germany'
    | 'france'
    | 'netherlands'
    | 'sweden'
    | 'japan'
    | 'south_korea'
    | 'ireland'
    | 'new_zealand'
    | 'singapore'
    | 'malaysia'
    | 'italy'
    | 'spain'
    | 'switzerland'
    | 'finland'
    | 'denmark'
    | 'norway'
    | 'other';
  city?: string | null;
  /**
   * University/institution you attend(ed).
   */
  university?: string | null;
  /**
   * Your current or completed degree level.
   */
  degree: 'bachelor' | 'master' | 'phd' | 'postdoc' | 'working' | 'language';
  /**
   * Your field or major.
   */
  fieldOfStudy?: string | null;
  /**
   * How many years you have been living abroad.
   */
  yearsAbroad?: number | null;
  /**
   * Services you offer to help students.
   */
  services?:
    | (
        | 'university_selection'
        | 'application_review'
        | 'sop_review'
        | 'visa_guidance'
        | 'scholarship'
        | 'interview_prep'
        | 'accommodation'
        | 'lifestyle_guide'
        | 'job_guidance'
        | 'language_test'
      )[]
    | null;
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Offer a free 15-min intro call for new students.
   */
  introCallFree?: boolean | null;
  /**
   * Session rate in USD per hour. Set 0 for free mentoring.
   */
  hourlyRate?: number | null;
  /**
   * Session lengths you are willing to offer.
   */
  sessionDurations?: ('30' | '45' | '60' | '90')[] | null;
  /**
   * IANA timezone string used for scheduling.
   */
  timezone?: string | null;
  /**
   * Days of the week when you typically take sessions.
   */
  availableDays?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  /**
   * Cap on weekly bookings to prevent overload.
   */
  maxSessionsPerWeek?: number | null;
  linkedin?: string | null;
  youtube?: string | null;
  instagram?: string | null;
  website?: string | null;
  /**
   * Incremented automatically when a session is marked complete.
   */
  totalSessions?: number | null;
  /**
   * Cumulative net earnings in USD after platform fees.
   */
  totalEarningsUSD?: number | null;
  /**
   * Average star rating (0–5). Recomputed on each new review.
   */
  rating?: number | null;
  /**
   * Total number of reviews received.
   */
  reviewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Student profiles — people who want to study abroad, linked via the user relationship.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentees".
 */
export interface Mentee {
  id: string;
  /**
   * The user account that owns this student profile.
   */
  user: string | User;
  /**
   * Profile photo.
   */
  profileImage?: (string | null) | Media;
  /**
   * Short bio — tell mentors about yourself and your study abroad plans.
   */
  bio?: string | null;
  /**
   * Your current education level.
   */
  currentEducation: 'high_school' | 'bachelor' | 'master' | 'working';
  /**
   * The degree level you want to pursue abroad.
   */
  targetDegree: 'bachelor' | 'master' | 'phd' | 'language' | 'foundation' | 'diploma';
  /**
   * The field or subject you want to study.
   */
  fieldOfInterest?: string | null;
  /**
   * Countries you are considering for study abroad.
   */
  targetCountry?:
    | (
        | 'usa'
        | 'uk'
        | 'canada'
        | 'australia'
        | 'germany'
        | 'france'
        | 'netherlands'
        | 'sweden'
        | 'japan'
        | 'south_korea'
        | 'ireland'
        | 'new_zealand'
        | 'singapore'
        | 'malaysia'
        | 'italy'
        | 'spain'
        | 'switzerland'
        | 'finland'
        | 'denmark'
        | 'norway'
        | 'other'
      )[]
    | null;
  /**
   * When do you plan to start studying abroad?
   */
  targetIntake?: string | null;
  /**
   * Your English language proficiency.
   */
  englishProficiency?:
    | (
        | 'native'
        | 'advanced'
        | 'intermediate'
        | 'basic'
        | 'preparing_ielts'
        | 'preparing_toefl'
        | 'has_ielts'
        | 'has_toefl'
      )
    | null;
  /**
   * Annual tuition budget range.
   */
  budgetRange?: ('full_scholarship' | 'under_10k' | '10k_25k' | '25k_50k' | 'over_50k' | 'flexible') | null;
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What kind of help are you looking for?
   */
  helpNeeded?:
    | (
        | 'university_selection'
        | 'application_review'
        | 'sop_review'
        | 'visa_guidance'
        | 'scholarship'
        | 'interview_prep'
        | 'accommodation'
        | 'lifestyle_guide'
        | 'job_guidance'
        | 'language_test'
      )[]
    | null;
  /**
   * Specific goals you want to achieve.
   */
  goals?:
    | {
        goal: string;
        /**
         * Optional target completion date.
         */
        targetDate?: string | null;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * IANA timezone string used for scheduling.
   */
  timezone?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  /**
   * Incremented automatically when a session is marked complete.
   */
  totalSessions?: number | null;
  /**
   * Total hours spent in completed sessions.
   */
  totalHoursLearned?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  mentor: string | Mentor;
  mentee: string | Mentee;
  mentorUser: string | User;
  menteeUser: string | User;
  topic: string;
  description?: string | null;
  scheduledAt: string;
  /**
   * Duration in minutes
   */
  duration: number;
  status: 'pending' | 'awaiting_payment' | 'confirmed' | 'completed' | 'cancelled';
  /**
   * Rate snapshot at booking time (USD)
   */
  hourlyRate: number;
  /**
   * Total charged to mentee (USD)
   */
  amountCharged: number;
  paymentMethod?: ('stripe' | 'sslcommerz' | 'bkash') | null;
  paymentStatus?: ('pending' | 'paid' | 'refunded' | 'failed') | null;
  /**
   * Payment gateway transaction ID (from webhook)
   */
  transactionId?: string | null;
  meetingLink?: string | null;
  notes?: string | null;
  rating?: number | null;
  review?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  session: string | Session;
  sender: string | User;
  senderName: string;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  session: string | Session;
  mentorUser: string | User;
  menteeUser: string | User;
  type: 'payment' | 'payout' | 'refund';
  grossAmount: number;
  platformFee: number;
  netAmount: number;
  status: 'pending' | 'completed' | 'refunded';
  updatedAt: string;
  createdAt: string;
}
/**
 * Mentor availability slots. Each document is a bookable time window.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: string;
  /**
   * The mentor profile this slot belongs to.
   */
  mentor: string | Mentor;
  /**
   * Start of available window.
   */
  startTime: string;
  /**
   * End of available window.
   */
  endTime: string;
  /**
   * True once a confirmed booking is attached to this slot.
   */
  isBooked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * WebRTC call session records. Created when a call starts, updated when it ends.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "call-sessions".
 */
export interface CallSession {
  id: string;
  /**
   * The booking this call is associated with.
   */
  booking: string | Session;
  /**
   * When the call was initiated.
   */
  startedAt: string;
  /**
   * When the call ended. Null if still active.
   */
  endedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mentor payout/withdrawal requests after session completion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawals".
 */
export interface Withdrawal {
  id: string;
  /**
   * The mentor requesting the withdrawal.
   */
  mentorUser: string | User;
  /**
   * Amount requested in USD.
   */
  amount: number;
  status?: ('pending' | 'processing' | 'completed' | 'rejected') | null;
  /**
   * Optional note from mentor or admin.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
    /**
     * Allow clients to create users.
     */
    create?: boolean | null;
    /**
     * Allow clients to update users.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete users.
     */
    delete?: boolean | null;
  };
  mentors?: {
    /**
     * Allow clients to find mentors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create mentors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update mentors.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete mentors.
     */
    delete?: boolean | null;
  };
  mentees?: {
    /**
     * Allow clients to find mentees.
     */
    find?: boolean | null;
    /**
     * Allow clients to create mentees.
     */
    create?: boolean | null;
    /**
     * Allow clients to update mentees.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete mentees.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * List mentor profiles with their headline, category, hourlyRate, rating, and skills.
     */
    getMentorProfiles?: boolean | null;
    /**
     * List mentee profiles with their target role, experience level, and learning goals.
     */
    getMenteeProfiles?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'mentors';
        value: string | Mentor;
      } | null)
    | ({
        relationTo: 'mentees';
        value: string | Mentee;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'availability';
        value: string | Availability;
      } | null)
    | ({
        relationTo: 'call-sessions';
        value: string | CallSession;
      } | null)
    | ({
        relationTo: 'withdrawals';
        value: string | Withdrawal;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors_select".
 */
export interface MentorsSelect<T extends boolean = true> {
  user?: T;
  profileImage?: T;
  isVerified?: T;
  isAvailable?: T;
  headline?: T;
  bio?: T;
  country?: T;
  city?: T;
  university?: T;
  degree?: T;
  fieldOfStudy?: T;
  yearsAbroad?: T;
  services?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  introCallFree?: T;
  hourlyRate?: T;
  sessionDurations?: T;
  timezone?: T;
  availableDays?: T;
  maxSessionsPerWeek?: T;
  linkedin?: T;
  youtube?: T;
  instagram?: T;
  website?: T;
  totalSessions?: T;
  totalEarningsUSD?: T;
  rating?: T;
  reviewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentees_select".
 */
export interface MenteesSelect<T extends boolean = true> {
  user?: T;
  profileImage?: T;
  bio?: T;
  currentEducation?: T;
  targetDegree?: T;
  fieldOfInterest?: T;
  targetCountry?: T;
  targetIntake?: T;
  englishProficiency?: T;
  budgetRange?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  helpNeeded?: T;
  goals?:
    | T
    | {
        goal?: T;
        targetDate?: T;
        completed?: T;
        id?: T;
      };
  timezone?: T;
  linkedin?: T;
  facebook?: T;
  totalSessions?: T;
  totalHoursLearned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  mentor?: T;
  mentee?: T;
  mentorUser?: T;
  menteeUser?: T;
  topic?: T;
  description?: T;
  scheduledAt?: T;
  duration?: T;
  status?: T;
  hourlyRate?: T;
  amountCharged?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  transactionId?: T;
  meetingLink?: T;
  notes?: T;
  rating?: T;
  review?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  session?: T;
  sender?: T;
  senderName?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  session?: T;
  mentorUser?: T;
  menteeUser?: T;
  type?: T;
  grossAmount?: T;
  platformFee?: T;
  netAmount?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  mentor?: T;
  startTime?: T;
  endTime?: T;
  isBooked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "call-sessions_select".
 */
export interface CallSessionsSelect<T extends boolean = true> {
  booking?: T;
  startedAt?: T;
  endedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawals_select".
 */
export interface WithdrawalsSelect<T extends boolean = true> {
  mentorUser?: T;
  amount?: T;
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  users?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  mentors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  mentees?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        getMentorProfiles?: T;
        getMenteeProfiles?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}